#page title
page_title                                : IPTV +                            # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1525121231                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
#presskit_download_link                    : https://emilbaehr.com                    # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Finally enjoy your ipTV content.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mohamed Ali                                
your_link                                 :                      
your_city                                 : Dubai                                
email_address                             : contact@iptvplus.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : by_mohamed_ali
github_username                           : byMohamedali
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Beautiful UI
    description                           : Watch your digital content, TV Live, Movies, and TV Shows with style!
    fontawesome_icon_name                 : magic

  - title                                 : Powerful stream player
    description                           : MP4, FLV, MOV, HLS... our fast and strong stream player handles every formats!
    fontawesome_icon_name                 : play-circle

  - title                                 : Enhanced search bar
    description                           : Search Movies, TV Series and Live channels!
    fontawesome_icon_name                 : search
    
  - title                                 : Settings page
    description                           : Your content, your settings, your customization. Enjoy our dark mode and others customizations just for you!
    fontawesome_icon_name                 : user-cog

  - title                                 : Multiple playlists support
    description                           : We never have enough content in a single playlist. Don't worry, we handle this for you, add as many playlists as you want.
    fontawesome_icon_name                 : stream

  - title                                 : ICloud synchronization
    description                           : All your data is synchronized on your Apple iCloud to make it available on all your devices and only accessible to you.
    fontawesome_icon_name                 : sync

  - title                                 : Subtitles selection
    description                           : Beautiful and easy to read subtitles to watch your original content.
    fontawesome_icon_name                 : closed-captioning
  
  - title                                 : Audio tracks selection
    description                           : From 'Bonjour' to 'こんにちは' in a single touch!
    fontawesome_icon_name                 : language

  - title                                 : Telegram group
    description                           : Join our telegram group to discuss about future features and so much more.
    fontawesome_icon_name                 : smile-beam



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#000"
feature_icons_background_color            : "#fff"

social_icons_foreground_color             : "#333333"
social_icons_background_color             : "#e3e3e3"

footer_text_color                         : "#333333"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown